### ISSUE TITLE
Improved validation errors

### ISSUE THREAD

**Issue by piersmacdonald** [gcanti/io-ts#194]
Currently the validation errors after decoding look something like this: `"Invalid value \"some_mock_id_type\" supplied to : ExactType<{ f....`.

This doesn't provide much useful information to give back to clients to help them get a better response. Looking at the validation objects you can tell them the value that was wrong but the property is hard to identify and if they're missing a field that's impossible to tell which one.

**Comment by gcanti** [comment]
> "Invalid value \"some_mock_id_type\" supplied to : ExactType<{ f.....

That's the output of the default error reporter, you can define your own. `Errors` has the following type

```ts
interface ContextEntry {
  readonly key: string
  readonly type: Decoder<any, any>
}
type Context = ReadonlyArray<ContextEntry>
interface ValidationError {
  readonly value: mixed
  readonly context: Context
}
type Errors = Array<ValidationError>
```

For example

```ts
import * as t from 'io-ts'

const getPaths = <A>(v: t.Validation<A>): Array<string> => {
  return v.fold(errors => errors.map(error => error.context.map(({ key }) => key).join('.')), () => ['no errors'])
}

const Person = t.type({
  name: t.string,
  age: t.number
})

console.log(getPaths(Person.decode({}))) // => [ '.name', '.age' ]
```

**Comment by mmkal** [comment]
@gcanti one thing that potentially is missing though is the ability to retrieve the object originally passed to `decode`. As far as I can tell there is no way to do `Person.decode({ foo: 'bar' })` and get the value `{ "foo": "bar" }` printed out anywhere. The `Validation` returned by decode contains information about the type, and the values that had errors, but not the original object passed in. With your example (using JSON.stringify as a pseudo-reporter since it prints out all the data available for any reporter):
```typescript
const Person = t.interface({ name: t.string });
console.log(JSON.stringify(Person.decode({ foo: 'bar', name: 1 }), null, 4));

// prints:
{
    "value": [
        {
            "value": 1,
            "context": [
                {
                    "key": "",
                    "type": {
                        "name": "{ name: string }",
                        "props": {
                            "name": {
                                "name": "string",
                                "_tag": "StringType"
                            }
                        },
                        "_tag": "InterfaceType"
                    }
                },
                {
                    "key": "name",
                    "type": {
                        "name": "string",
                        "_tag": "StringType"
                    }
                }
            ]
        }
    ],
    "_tag": "Left"
}
```

While I can understand why the `foo` property is less relevant here, it'd be useful information when debugging real-life failures. We get situations like where we think an api will respond `{ name: 'foo' }` but it actually responds `{ data: { name: 'foo' } }`. Getting an error telling us `name` is undefined doesn't help us figure out how to fix the problem.

The best I've come up with for now is very hacky:
```typescript
Object.assign(
    t.Type.prototype,
    {
        decode: function (i: any) {
            const type: Type<any> = this as any;
            return type.validate(i, [{ key: JSON.stringify(i), type }]);
        }
    },
);
```
This uses the full object JSON as a 'key', which is clearly an abuse of that field. What do you think is the best way to not lose this information? (presumably not this!)

**Comment by gcanti** [comment]
@mmkal you are right, that information is missing. I'm afraid the `Validation` type is focused on errors, so if you want richer reports you need a proxy function, something along the lines of

```ts
decode: <A>(m: t.mixed, type: t.Decoder<t.mixed, A>) => Either<string, A>
```

For example

```ts
import * as t from 'io-ts'
import { failure } from 'io-ts/lib/PathReporter'

const decode = <I, A>(input: I, type: t.Decoder<I, A>) => {
  return type.decode(input).mapLeft(
    errors => `Validation failed for input:

${JSON.stringify(input, null, 2)}

Error details:

${failure(errors)
      .map(s => '- ' + s)
      .join('\n')}
`
  )
}

const Person = t.interface({ name: t.string }, 'Person')
console.log(decode({ foo: 'bar', name: 1 }, Person).fold(s => s, () => 'no errors'))
```

Output:

```
Validation failed for input:

{
  "foo": "bar",
  "name": 1
}

Error details:

- Invalid value 1 supplied to : Person/name: string
```

**Comment by mmkal** [comment]
Any chance this could make it into the library so we wouldn't have to make sure we never used vanilla `decode`? It could be done in a non-breaking way by adding a `data?: any` property to `ContextEntry`. It'd only need to be present in the first context entry. Or it could become a union type

`{ key: string, type: Decoder<any, any> } | { data: any, type: Decoder<any, any> }`

this might make more sense since it's already a little weird/hacky that `getDefaultContext` uses an empty string for `key` when `validate` is called: https://github.com/gcanti/io-ts/blob/1dbcd2b5730255f384591fc0c7d0bbfba52697d3/src/index.ts#L93

It could instead become
```typescript
export const getDefaultContext = (data: any, type: Decoder<any, any>): Context => [{ data, type }]
```

**Comment by gcanti** [comment]
@mmkal what about adding the input data to `ValidationError` instead?

```ts
export interface ValidationError {
  readonly value: unknown
  readonly context: Context
  readonly actual?: unknown
}
```

**Comment by samal-rasmussen** [comment]
getPaths using modern pipe syntax:
```
import { fold } from 'fp-ts/lib/Either'
import { pipe } from 'fp-ts/lib/pipeable'
import * as t from 'io-ts'

const getPaths = <A>(v: t.Validation<A>): Array<string> => {
  return pipe(
    v,
    fold(
      (errors) =>
        errors.map((error) => error.context.map(({ key }) => key).join('.')),
      () => ['no errors']
    )
  )
}
```
