### ISSUE TITLE
expose 'getProps'

### ISSUE THREAD

**Issue by sledorze** [gcanti/io-ts#236]
Here:

https://github.com/gcanti/io-ts/blob/master/src/index.ts#L1294

**Comment by sledorze** [comment]
Motivation: https://github.com/gcanti/fp-ts-routing/pull/38#issuecomment-441311672

**Comment by gcanti** [comment]
`getProps` is an internal API and should be kept private. 

Also, it's not even complete (with respect to runtime types with "extractable" props) since lacks support for exact types

**Comment by evaera** [comment]
This would be useful to me as well. I have a command that configures one data point at a time and needed a way to validate that a given key was a valid property name of the configuration Type. My custom configuration Type is made up of intersections of intersections of partial and regular types so it's more ergonomic to just use this function instead of checking `.props` of each InterfaceType individually.

If the current `getProps` is incomplete, would it be possible to create a more complete user-facing version or fix the current one? I'd rather this function come from the library instead of maintaining my own utility since it is more deeply coupled with the internal implementation of the various Types.
