### ISSUE TITLE
Deprecate taggedUnion in favour of a smarter implementation of union

### ISSUE THREAD

**Issue by gcanti** [gcanti/io-ts#254]
Tagged unions could be auto-detected by `union`.

**Comment by Magellol** [comment]
I see that `union` is now [capable](https://github.com/gcanti/io-ts/blob/a1e46b46f706bda1ced0d40890a7916b70f6a146/CHANGELOG.md#190) of detecting the tags automatically. We currently use `taggedUnion` and we were hoping to migrate to use `union` instead. Although, we also leverage a bunch of helpers you had previously shared in here https://github.com/gcanti/io-ts/pull/183#issue-196939269 but we're not able to make the type matching anymore since it seems that `UnionC` doesn't know about a `tag` property and all of these helpers require a `TaggedUnionC`.

Do you have any guidance?

**Comment by Magellol** [comment]
@gcanti I was also curious about the `getIndex` internal function. We're using it as part of some of the helpers to create constructors and type guards. Do you have any plans on exporting it officially?

**Comment by gcanti** [comment]
@Magellol development of stable APIs is frozen because I'm switching to a different model for decoders / encoders (see the new experimental modules in v2.2) which don't rely on meta infos like `tag`, `props`, etc...

> Do you have any guidance?

Stay with `taggedUnion`, if I understand correctly there's no tangible benefit in switching to `union` in your case.

> Do you have any plans on exporting it officially?

No, but as I said above development is frozen so you can reasonably rely on it.
