### ISSUE TITLE
Error since upgrading to 1.6.1

### ISSUE THREAD

**Issue by quentez** [gcanti/io-ts#263]
We're making extensive use of Tagged Unions, and since upgrading to 1.6.1 we're now getting an error right when we declare our types:

![image](https://user-images.githubusercontent.com/504055/51283285-8e081e00-199c-11e9-93f4-6bb1f77001de.png)

Everything was working well in 1.6.0.

Our use-case in that file is pretty big and I can't just post it here. I'll have to try and reproduce it with a simpler case. The only thing I can see right now is that we're building a Tagged Union of Intersections (with the tag property being in one branch of the intersection).

**Comment by gcanti** [comment]
@quentez looks like the issue is also related to `io-ts` not being able to build a tagged union in some conditions.

> We're making extensive use of Tagged Unions

I need your help, I just released a patch (`1.6.4`) that should fix this issue. 
I also added a warning to the console if I can't build a tagged union.

Example

```ts
const A = t.type({ type: t.literal('A'), a: t.number }, 'A')
const B = t.refinement(A, x => x.a > 0, 'B')
const T = t.taggedUnion('type', [B, A]) // type-checks but T is not a tagged union
```

In this case `taggedUnion` does two things:

- prints to the console a warning (like `"[io-ts] Cannot build a tagged union for (B | A), returning a de-optimized union"`)
- returns a de-optimized `union`

Could you please try it out?

**Comment by quentez** [comment]
@gcanti Version `1.6.4` is working without any issue.
(And I'm not seeing the warning, so that's good).

Thank you for the super quick turnaround 🙂 !

**Comment by gcanti** [comment]
@quentez great, thanks for the bug report and the feedback
