### ISSUE TITLE
[RFC] deprecate refinement (and Integer)

### ISSUE THREAD

**Issue by gcanti** [gcanti/io-ts#265]
Motivation: `refinement`s are inherently unsafe

Example

```ts
const PositiveInt = t.refinement(t.Integer, n => n > 0, 'PositiveInt')

const Person = t.type({
  name: t.string,
  age: PositiveInt
})

type Person = t.TypeOf<typeof Person>

const person: Person = {
  name: 'name',
  age: -1.2 // <= no errors
}
```

I propose to deprecate `refinement` in favour of a `brand` combinator

Definition

```ts
declare const _brand: unique symbol

export interface Brand<B> {
  readonly [_brand]: B
}

export interface BrandC<C extends t.Any, B>
  extends t.RefinementType<C, t.TypeOf<C> & Brand<B>, t.OutputOf<C>, t.InputOf<C>> {}

// replaces refinement
export const brand = <C extends t.Any, B extends string>(
  codec: C,
  predicate: Predicate<t.TypeOf<C>>,
  name: B
): BrandC<C, B> => {
  return t.refinement(codec, predicate, name)
}

// replaces Integer
export const Int = brand(number, n => n % 1 === 0, 'Int')
```

Usage

```ts
// const Int: BrandC<t.NumberC, "Int">
const Int = brand(t.number, n => n % 1 === 0, 'Int')
// type Int = number & Brand<"Int">
type Int = t.TypeOf<typeof Int>

const Positive = brand(t.number, n => n > 0, 'Positive')
// type Positive = number & Brand<"Positive">
type Positive = t.TypeOf<typeof Positive>

const PositiveInt = t.intersection([Int, Positive])
// type PositiveInt = number & Brand<'Int'> & Brand<'Positive'>
type PositiveInt = t.TypeOf<typeof PositiveInt>

import { PathReporter } from 'io-ts/lib/PathReporter'

console.log(PathReporter.report(PositiveInt.decode(1.1)))
// [ 'Invalid value 1.1 supplied to : (Int & Positive)/0: Int' ]
console.log(PathReporter.report(PositiveInt.decode(-1)))
// [ 'Invalid value -1 supplied to : (Int & Positive)/1: Positive' ]

const Person = t.type({
  name: t.string,
  age: PositiveInt
})

type Person = t.TypeOf<typeof Person>

const p: Person = {
  name: 'Giulio',
  age: -1.2 // Type 'number' is not assignable to type 'Brand<"Int">
}
```

The `brand` signature is almost identical to `refinement` (the `name` argument is required though).

The migration path should be straightforward and incremental: you can switch to `brand`, one refinement at the time, and fix the possible type-checking errors that could happen.

**Comment by leemhenson** [comment]
Yeah "ad-hoc branding" is something I'm doing a lot now, pending https://github.com/Microsoft/TypeScript/issues/202 resulting in something less boilerplatey, like `type PositiveInt = unique number`. I've been casting to the brand in my io-ts types, so this combinator feels pretty natural to me.

**Comment by gcanti** [comment]
> Yeah "ad-hoc branding" is something I'm doing a lot now

@leemhenson that's great, your early feedback would be much appreciated, you can try the release candidate by running `npm i gcanti/io-ts#1.8.0-lib`

**Comment by leemhenson** [comment]
Works as expected and saves me a bit of boilerplate! 👍

**Comment by lostintime** [comment]
I'm using refined types a lot, but had to implement own type and combinator:

```typescript
import { AnyNewtype, Newtype } from "newtype-ts"
import * as t from "io-ts"

export type Refined<_URI extends { readonly [K in symbol | string | number]: symbol }, A> =
  A & Newtype<_URI, A>

export function refine<T extends AnyNewtype, RT extends t.Type<T["_A"]>>(
  rt: RT,
  isT: (val: t.OutputOf<RT>) => val is T,
  name: string
): t.Type<T, T, t.InputOf<RT>> {
  return new t.Type(
    name,
    (val: t.InputOf<RT>): val is T => rt.is(val) && isT(val),
    (val, ctx) => rt.decode(val).filterOrElseL(isT, _ => [t.getValidationError(_, ctx)]),
    t.identity
  )
}
```

But the issue with this is that it's _legal_ to access the `_URI` property and then compiler will not scream `unique symbol` field name fixes this and is also shorter to write type definitions.

It may be also useful to have a `Refined` (or `Branded`) type exported by `io-ts` so it can be used to declare types explicitely*, ex: 

```typescript
export type Refined<A, Tag extends string> = A & Brand<Tag>

type Int = t.Refined<number, "Int">
```

_*I'm often declaring types explicitly rather than extracting with `t.TypeOf`, to avoid 'uge definition files (I know it was improved in latest versions: https://github.com/gcanti/io-ts/issues/165)_

Hope to see this functionality in next minor release 👍.

**Comment by gcanti** [comment]
> It may be also useful to have a Refined (or Branded) type exported by io-ts so it can be used to declare types explicitely

@lostintime what's the use case? Let's say we define `Positive`

```ts
const Positive = t.brand(t.number, n => n > 0, 'Positive')

type Positive = t.TypeOf<typeof Positive>
/*
same as
type Positive = number & t.Brand<"Positive">
*/
```

How would you use a `Branded` type?

```ts
export type Branded<A, B> = A & Brand<B>
```

**Comment by lostintime** [comment]
@gcanti as I mentioned - I'm currently defining types explicitly, then adding decoders for them, to get cleaner error messages, and less verbose definition files, ex:

```typescript
type UserId = t.Branded<string, "UserId">

const UserId: t.Type<UserId> = t.brand(t.number, _ => true, "UserId") 

type User = {
  userId: UserId
  name: string
}

const User: t.Type<User> = t.interface({
  userId: UserId,
  name: t.string
})
```

Maybe that's not the case for `t.brand` (or it depends on parent type verbosity), but in order to keep code style consistent I think I'd be using same for refined too.

My approach have some other pitfalls also - for types with optional values - you may forget to add some fields to decoders and compiler will not complain :(, that's why I was searching long time for a way to pass explicit types parameters to decoders also, ex:

```typescript
const User: t.Type<User> = t.interface<User>({...})
```
but it doesn't work this way, full decoder type is expected.

For example this definition:

```typescript
export const Person = t.interface({
  name: t.intersection([
    t.interface({
      firstName: t.string,
      lastName: t.string
    }),
    t.partial({
      middleName: t.string
    })
  ]),
  cityName: t.string
})

export const MyPersons = t.interface({
  something: t.string,
  persons: t.array(Person)
})
```

generates this definition (using `io-ts@1.7.1`): 
```typescript
export declare const Person: t.TypeC<{
    name: t.IntersectionC<[t.TypeC<{
        firstName: t.StringC;
        lastName: t.StringC;
    }>, t.PartialC<{
        middleName: t.StringC;
    }>]>;
    cityName: t.StringC;
}>;

export declare const MyPersons: t.TypeC<{
    something: t.StringC;
    persons: t.ArrayC<t.TypeC<{
        name: t.IntersectionC<[t.TypeC<{
            firstName: t.StringC;
            lastName: t.StringC;
        }>, t.PartialC<{
            middleName: t.StringC;
        }>]>;
        cityName: t.StringC;
    }>>;
}>;

```

And it gets worse when composing types.

**Comment by gcanti** [comment]
Ah, so you are not satisfied by the type of the codec itself... 

you are writing the schema twice though

```ts
// 1)
type User = {
  userId: number
  name: string
}

// 2)
const User: t.Type<User> = t.type({
  userId: t.number,
  name: t.string
})
```

What about this pattern?

```ts
const _User = t.type({
  userId: t.number,
  name: t.string
})
interface User extends t.TypeOf<typeof _User> {}
const User: t.Type<User> = _User
```

Works with brands too

```ts
const _UserId = t.brand(t.number, _ => true, 'UserId')
type UserId = t.TypeOf<typeof _UserId>
type UserIdO = t.OutputOf<typeof _UserId>
const UserId: t.Type<UserId, UserIdO> = _UserId
```

**Comment by lostintime** [comment]
The described pattern solves the issue with verbose definitions and makes code less vulnerable to human factor issue I described above, which is much much better.

There are still few pros to using explicit types:

You get better IDE hints:

<img width="443" alt="screen shot 2019-02-04 at 11 33 18" src="https://user-images.githubusercontent.com/722841/52200832-6fe25f00-2872-11e9-9d4a-6d8a2f2d5090.png">

vs:

<img width="458" alt="screen shot 2019-02-04 at 11 34 59" src="https://user-images.githubusercontent.com/722841/52200908-9ef8d080-2872-11e9-9113-ebfe490a8611.png">

and field comments:

<img width="258" alt="screen shot 2019-02-04 at 11 34 44" src="https://user-images.githubusercontent.com/722841/52200934-b20ba080-2872-11e9-90e1-cfdee205146b.png">

And you can also define decoders for _external_ types, I mean - there is still place for the way I'm using it.

Anyway, this is probably not the best place to discuss this issue :)

On the _refined_ topic - I don't think this should stop the progress with new `brand` combinator, I can add type alias locally (or even inline it as `T & t.Brand<"Name">`) until (_and if_) it will added to the library.

**Comment by gcanti** [comment]
Released https://github.com/gcanti/io-ts/releases/tag/1.8.0

**Comment by JalilArfaoui** [comment]
@gcanti  My issue with using `type User = t.TypeOf<typeof _User>` is that it makes my domain types depend on my Codec types … which is an issue to me because I’m trying to apply hexagonal architecture, but also because my domain types leave in a `domain` lib whereas I’m trying to implement my io-ts codecs in an `api` adapter lib …

I’m not sure how I can parse branded fields now without a proper and well typed `refinement` … ?
