### ISSUE TITLE
Results of is and decode do not match

### ISSUE THREAD

**Issue by helmutkian** [gcanti/io-ts#328]
The behavior of `#is` and `#decode` diverge when dealing with properties that may be undefined. See: 

````typescript
const T = t.type({
  a: t.string,
  b: t.union([t.string, t.undefined])
})

// Unexpected result
T.is({ a: 'foo' }) // => false
T.decode({ a: 'foo' }).isRight() // => true

// Works as expected
T.is({ a: 'foo', b: undefined }) // => true
T.decode({ a: 'foo', b: undefined }).isRight() // => true
````

This is unexpected, since you would assume anything for which `#decode` returns `Right` should also pass the type guard.

**Comment by gcanti** [comment]
> since you would assume anything for which #decode returns Right should also pass the type guard

You can't assume that for a `Type<A, O, I>` codec: while `decode` can change the result type

```ts
decode: (input: I) => Either<Errors, A>
```

`is` is just a custom type guard

```ts
is: (u: unknown) => u is A
```

Indeed you can't derive `is` from `decode` since, in general, `A` can be different from `I`/`O` and `I` can be different from `unknown`.

The following example shows the difference (`NumberFromString` from [io-ts-types](https://github.com/gcanti/io-ts-types))

```ts
const NumberFromString = new t.Type<number, string, string>(
  'NumberFromString',
  (u: unknown): u is number => typeof u === 'number',
  (u, c) =>
    t.string.validate(u, c).chain(s => {
      const n = +s
      return isNaN(n) ? t.failure(s, c) : t.success(n)
    }),
  String
)

NumberFromString.decode('1') // returns right(1)
NumberFromString.is('1') // returns false
NumberFromString.is(1) // returns true
```
