### ISSUE TITLE
module not found: Can't resolve 'fp-ts/lib/Either' in

### ISSUE THREAD

**Issue by steida** [gcanti/io-ts#341]
Last working version is 1.9.0

**Comment by gcanti** [comment]
https://github.com/gcanti/io-ts/issues/337

**Comment by RHolland13** [comment]
This broke a number of our nightly CI builds for packages that were depending on io-ts indirectly through a released package.  We never imported from fp-ts, and therefore did not list it as a dependency.  It seems to me like a change that requires all downstream consumers to make an update to their package.json in order to continue building should be considered non-passive and warrant a major version bump.

**Comment by jjant** [comment]
Same thing happened to us

**Comment by steida** [comment]
Check https://github.com/gcanti/io-ts#installation It works for me.

**Comment by gcanti** [comment]
> We never imported from fp-ts, and therefore did not list it as a dependency. It seems to me like a change that requires all downstream consumers to make an update to their package.json in order to continue building should be considered non-passive

@RHolland13 I agree, I'll revert that change.

**Comment by gcanti** [comment]
Patch released https://github.com/gcanti/io-ts/releases/tag/1.10.2

**Comment by alcuadrado** [comment]
Thanks for fixing this @gcanti.

We are ok with this change if you reintroduce it in a major version.
