### ISSUE TITLE
io-ts seems to have 2 kinds of codecs which don't mix well together. 

### ISSUE THREAD

**Issue by loxs** [gcanti/io-ts#371]
I find myself having written 2 different functions to verify entities that are subjects to my codecs and I struggle to find ways to type one single function that can do both. 

```typescript
export const verifyIOObject = <T extends {}>(obj: any, codec: t.TypeC<T>) =>
  isRight(codec.decode(obj));

export const verifyIOEntity = <T>(toVerify: unknown, codec: t.Type<T>) =>
  isRight(codec.decode(toVerify));
```

Seems like the first one is able to verify codecs that are written with `t.type(...props)` and the other, codecs that are written any other way.

Even if I have a codec that uses `t.union([CodecA, CodecB], 'myField')` where both CodecA and CodecB are defined using `t.type(...props)`, my code fails to compile if I try to verify its entities using `verifyIOObject`

What am I not getting right? Is it possible to write a verification function that accepts both types of codecs?

**Comment by giogonzo** [comment]
I see a few different issues with the code above, all stemming from a single possible misunderstanding. A generic io-ts codec has two (actually three, but let's ignore the last one for now) type parameters:

```ts
t.Type<A, O>
```
`A` represents the type of the decoded value
`O` represents the type of the encoded value (`O`utput)

So e.g., for `t.string`, you have both `A` and `O` = `string`.

But this is not true in general, take for instance `DateFromISOString` from `io-ts-types`: here we have `A` = `Date`, but `O` = `string`.

This means that, in general, the input and (successful) `decode` output might differ.

Given the above, I see two issues with your functions above:

- To express "they'll accept any io-ts codec", you should have two free type params `A` and `O` (not just one, `T`)
- if a value decodes correctly, it doesn't mean (again, in general) that the input was of the type `T` that you are expecting once decoded

In addition to the above, the two functions don't seem to be really useful since there's no type information that is carried outside of it in case of success/failure, so the caller won't see (at the type level) any effect of the positive/negative "validation" after having called it.

With [TS 3.7](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-beta/) "assert functions" this could be expressed more easily. For the time being, if you want to see the effects in terms of control flow of the successful validation, you have to use something like:

```ts
import { fold } from "fp-ts/lib/Either";
import { identity } from "fp-ts/lib/function";

export const verifyIOValue = <A, O>(obj: unknown, codec: t.Type<A, O>): A =>
  pipe(
    codec.decode(obj),
    fold(err => {
      throw err;
    }, identity)
  );

const decodedValue: string = verifyIOValue({}, t.string);
const decodedDate: Date = verifyIOValue("2019-10-02", DateFromISOString);
```

hope this helps 😄

**Comment by loxs** [comment]
In my case, not getting the decode type is OK, as I just verify that the user has sent an allowed type and write it to the database. I don't need to know what type exactly is sent.

I kind of know about the encoded and decoded types and I experimented quite a lot and the above was the one version that worked for men (given that I figured out which type of codec I'm dealing with).

Even with your function it doesn't work. Here is a full example:

```typescript
import * as t from 'io-ts';
import { identity } from 'io-ts';
import { fold, isRight } from 'fp-ts/lib/Either';
import { pipe } from 'fp-ts/lib/pipeable';

const CTurtle = t.type({ scales: t.literal(true), shell: t.literal(true), legs: t.literal(4) });
const CLizard = t.type({ scales: t.literal(false), shell: t.literal(false), legs: t.literal(4) });

const CReptile = t.union([CTurtle, CLizard]);

const CDog = t.type({ legs: t.literal(4), hair: t.literal(true) });

type CodecName = 'reptile' | 'dog';

const getCodec = (codecName: CodecName) => {
  if (codecName === 'reptile') {
    return CReptile;
  }
  return CDog;
};

const verifyIOValue = <A, O>(obj: unknown, codec: t.Type<A, O>): A =>
  pipe(
    codec.decode(obj),
    fold(err => {
      throw err;
    }, identity)
  );

const verifyAnyCodec = (codecName: CodecName, input: unknown) => {
  const codec = getCodec(codecName);
  return verifyIOValue(input, codec);
};
```

I get: 

```
Error:(32, 31) TS2345: Argument of type 'UnionC<[TypeC<{ scales: LiteralC<true>; shell: LiteralC<true>; legs: LiteralC<4>; }>, TypeC<{ scales: LiteralC<false>; shell: LiteralC<false>; legs: LiteralC<4>; }>]> | TypeC<{ ...; }>' is not assignable to parameter of type 'Type<{ scales: true; shell: true; legs: 4; } | { scales: false; shell: false; legs: 4; }, { scales: true; shell: true; legs: 4; } | { scales: false; shell: false; legs: 4; }, unknown>'.
  Type 'TypeC<{ legs: LiteralC<4>; hair: LiteralC<true>; }>' is not assignable to type 'Type<{ scales: true; shell: true; legs: 4; } | { scales: false; shell: false; legs: 4; }, { scales: true; shell: true; legs: 4; } | { scales: false; shell: false; legs: 4; }, unknown>'.
    Types of property 'is' are incompatible.
      Type 'Is<{ legs: 4; hair: true; }>' is not assignable to type 'Is<{ scales: true; shell: true; legs: 4; } | { scales: false; shell: false; legs: 4; }>'.
        Type '{ legs: 4; hair: true; }' is not assignable to type '{ scales: true; shell: true; legs: 4; } | { scales: false; shell: false; legs: 4; }'.
          Type '{ legs: 4; hair: true; }' is missing the following properties from type '{ scales: false; shell: false; legs: 4; }': scales, shell
```

**Comment by giogonzo** [comment]
> In my case, not getting the decode type is OK, as I just verify that the user has sent an allowed type and write it to the database. I don't need to know what type exactly is sent.

If this is the case, the verify function can just become

```ts
const verifyIOValue = (obj: unknown, codec: t.Mixed): boolean
```

**Comment by loxs** [comment]
Funny it would be called Mixed :D
