### ISSUE TITLE
rename `object` combinator

### ISSUE THREAD

**Issue by gcanti** [gcanti/io-ts#6]
`object` is a type in TypeScript 2.2

Proposal

- `object` to `record` 
- `ObjectType` to `RecordType`
- `Object` to `Pojo`

**Comment by dmorosinotto** [comment]
Hi @gcanti , maybe I am a bit 'late, but I don't totally agree with the rename you have made in the last commit. I understand the naming convention that you're adopting is very close to the typical Function Programming nomenclature, but I find the old naming more intuitive from a TS and Javascript perspective:
 `Pojo` -> `Object`
 `records(...)` -> `object (...)`
because in my opinion it is more clear what is checked in the validation (now it basically checks `typeof v = "object"` + Props definition) following the same matching concept of other types. 
And more than that, if in a "near future" we want to try to implement a "semi-automatic" runtime type-check based on this library (maybe using the reflect-metadata structure, or basic JS introspection via typeof) you will find that the native type is Object or "type", so in my opinion it may help to have a matching name...

I hope you can consider this "regression". 
And another small note, I saw that on npm the published version is the old 0.0.2, while the commit that you published bump the package ver to 0.1.0, but if you keep the renaming changes you are introducing a breaking change, so maybe you can bump ver number to 1.0.0 to correctly follow server.
BR Daniele

**Comment by gcanti** [comment]
> Hi @gcanti , maybe I am a bit too late

Hi, definitely you are not!

Not sure what are you proposing though, you don't agree with the renaming `t.record(...) -> t.object(...)`, with `t.Pojo -> t.Object` or both?

The original issue here is that `object` is now a new official type in TypeScript 2.2 so in order to be consistent I must rename `t.object` anyway, `record` seems ok but I'm open to suggestions.

> you are introducing a breaking change

AFAIK with respect to semver before hitting `1.0.0` a minor bump *does* signal a breaking change

**Comment by dmorosinotto** [comment]
Hi @gcanti , thanks for the quick response, I'm suggesting to rollback both rename to have a consistent naming. 
I don't understand the 
> issue here is that object is now a new official type in TypeScript 2.2 so in order to be consistent I must rename t.object anyway, record
I know that 2.2 will introduce `object` type that exactly describe what you will describe with `t.object` if I don't miss-understood the 2.2RC announce TS object is a "more strict" `any` excluding primitive types (string, number, bool ...) and so one more time `t.object` seem to me a perfect name match, or you have any problem to declare a function named object in 2.2?, currently I haven't download the new code and haven't tried to use the 2.2RC, maybe something is broken and giving you error for this!?

About the semver note, you are totally right that in the 0.x version there is no breaking change, but I like to think of it in an consistent way and start project ver with 1.0 from day 0 ...
But anyway if we'll agree in a regression rename, maybe there will be NO breaking-change at all 😄

**Comment by gcanti** [comment]
> I know that 2.2 will introduce object type that exactly describe what you will describe with `t.object`

I think that

```ts
const Person = t.record({
  name: t.string
})
```

is more like

```ts
type Person = {
  name: string
};
```

which is the type you get if you apply the `TypeOf` operator

```ts
type IPerson = TypeOf<typeof Person>;

// same as
type IPerson = {
  name: string
};
```

Moreover `object` accepts arrays and can't be "indexed"

```ts
const o1: object = { a: 1 }
const o2: object = null // error
const o3: object = undefined // error
const o4: object = [] // NO error
const o5: object = 1 // error

for (let k in o1){} // error: The right-hand side of a 'for...in' statement must be of type 'any', an object type or a type parameter
const k: keyof typeof o1 = 'a' // error: Type '"a"' is not assignable to type '"constructor" | "toString" | "toLocaleString" | "valueOf" | "hasOwnProperty" | "isPrototypeOf" | ...'
```

For what concerns the `t.Object -> t.Pojo` renaming, I noticed that

```ts
const o1: Object = {}
const o2: Object = null // error
const o3: Object = undefined // error
const o4: Object = [] // NO error
const o5: Object = 1 // NO error
```

so strictly speaking `Pojo !== Object`.

> About the semver note, you are totally right that in the 0.x version there is no breaking change signal by bump version

Actually there is, I mean if you have `"io-ts": "^0.0.2"` in your `package.json`, by bumping `io-ts` to `0.1.0` you don't get the new version (if I'm not wrong). In `0.x` releases, every minor bump is a considered a breaking change by npm.

> but I like to think of it in an consistent way and start project ver with 1.0 from day 0

This package is 12 days old, seems a bit premature to hit version 1.0.0. I propose to consolidate the APIs first and then publish a stable version as soon as possible.

**Comment by gcanti** [comment]
@dmorosinotto btw being a fellow italian may I suggest to also join the ItaliaJS slack here https://italiajs.slack.com? There is a `compile-to-js` channel in which we talk about TypeScript and other AltJS languages ;)

**Comment by dmorosinotto** [comment]
@gcanti Yes I'll definitely do, can you invite me in the slack channel?

**Comment by dmorosinotto** [comment]
About the issue, for me `t.object(...)` sound "more precise" or simply makes me "more confident of" than `t.record(...)` because it follow the same "standard" that you use in other basic validation, in that function you are asserting that typeof ="object" excluding other base-primitive types and Array, that sound to me the same as the new TS `object` type - but maybe I'm wrong, I'll have to take time to test all the cases that you posted to have a correct understand of the new type-check situation with TS 2.2

And about the `Pojo` export I think that what you are describing is a `t.mapping(t.string, t.Any)` and so why not simply use that instead of t.Object, or for duality/consistent with other cases just expose the old `const objectType`? 

Finally about the semver discussion, I understood your motivation about stabilizing api before hitting 1.0, I'm just a bit lazy and prefer to have evidence of breaking changes from day 0 (and so I suggest to start from 1.0), but the maintainer of the repo and package so you can decide whatever you want about visioning, not real a big problem for me, I'll keep reading change-log and commit to understand if there is something to be awere of ;-)

**Comment by gcanti** [comment]
> And about the Pojo export I think that what you are describing is a `t.mapping(t.string, t.Any)`

You are absolutely right, but

- I'm using `Pojo` in its implementation https://github.com/gcanti/io-ts/blob/master/src/index.ts#L312
- in practice `Pojo` is more useful than `Object` (often you don't want arrays when you type check objects)

> I'm just a bit lazy and prefer to have evidence of breaking changes

You will: before hitting 1.0.0 if you see a minor bump you know that there is breaking change
