### ISSUE TITLE
How to check if an Error is a DecoderError?

### ISSUE THREAD

**Issue by florianbepunkt** [gcanti/io-ts#620]
Not sure if this is a feature request or something missing in the docs (or something I have overlooked)

When using `Decoder` in some functions I have the following return type signature

```ts
declare function doSomething(): E.Either<DomainError1, DomainError2, DecoderError, A>

// desired
const st = doSomething();
Decoder.isDecoderError(st.left) ? "Failed decoding" : "A Domain Error"
```

How can I check whether an error is an DeoderError? I would like to handle ui different based on the error type, especiall use Decoder.draw for DecoderErrors, but for this I need a predicate for a DecoderError to distinguish it from other domain errors. How can this be done?

**Comment by samhh** [comment]
A more idiomatically functional approach, at least in the Haskell style, is to avoid the use of a union in the first place. Instead of `DomainError1 | DomainError2 | DecoderError`, you have a single sum type whose constructors represent each of these possibilities - in TypeScript almost certainly implemented as a tagged union, either directly or via a library. This bypasses the need to test the data itself at runtime.

For example, using [@unsplash/sum-types](https://github.com/unsplash/sum-types):

```ts
type DomainErr
  = Sum.Member<'FailedDecode', DecoderError>
  | etc

declare const f: IOEither<DomainErr, A>

pipe(f, IOE.match(
  DomainErr.match({
    FailedDecode: 'Failed decoding',
    [Sum._]: 'A domain error',
  }),
  happyPathFn,
))
```

**Comment by florianbepunkt** [comment]
@samhh Thank you, this is a sound approach, but there are other systems involved, so I would like to avoid wrapping "third-pary" errors, if possible.

**Comment by mlegenhausen** [comment]
@florianbepunkt there is a longer discussion about that in the [fp-ts issue tracker](https://github.com/gcanti/fp-ts/issues/904#issuecomment-572408690) maybe you take a look.

But the proposed solution from @samhh is the most robust and I would also recommend to go the extra mile.

**Comment by florianbepunkt** [comment]
Thank you @mlegenhausen and @samhh. This was very helpful.
