### ISSUE TITLE
io-ts/Decoder.<anyPrimitivetype>.decode is returning "any"

### ISSUE THREAD

**Issue by amplifications** [gcanti/io-ts#641]
### Current Behavior

`decode` is returning `any'. 

### Expected behavior

`decode` should return the the relevant `t.Validation<A>`

### Reproducible example

Screenshot shows the problem
<img width="612" alt="image" src="https://user-images.githubusercontent.com/67450976/161918545-1295be1b-5cf8-4b85-a553-737b76fb1f6d.png">

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |     2.2.16       |
| fp-ts      |     2.11.9       |
| TypeScript |   4.6.3         |

**Comment by samhh** [comment]
I think it's an issue with your environment/editor:

![2022-04-06T12:41:45,647112834+01:00](https://user-images.githubusercontent.com/6402443/161967163-94e40fb7-99f8-4a38-b818-11110fc3d00d.png)

**Comment by amplifications** [comment]
Thanks @samhh.

But everything else from fp-ts and io-ts seems to be type-checking properly.

I suspect it is related to https://github.com/gcanti/io-ts/issues/505#issuecomment-667760569

Not sure if that was identified .. or there might be another issue.

Looking for any further directions to debug/look into

**Comment by enricopolanski** [comment]
Consider providing compiler rather than editor feedback.

**Comment by amplifications** [comment]
Attempted to see if any compiler errors pops out .. but since this was only a type error, nothing was flagged during the compilation process. And compiled correctly to .js.

But, when I looked at the editor again, the typing in editor _appears to have fixed itself_.

<img width="495" alt="image" src="https://user-images.githubusercontent.com/67450976/162097565-42073d86-2d46-42a3-9ba4-36721a794690.png">

For now, will treat this as a non reproducible issue and close this. Will reopen if I find anything more.

Thanks everyone!

**Comment by ljani** [comment]
I'm testing [TypeScript 4.7 beta](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/) with native ESM support and I'm facing the same problem, except I'm getting `unknown`.

Here's [my sandbox](https://codesandbox.io/s/test-tth5op?file=/index.ts). Notice how `T` is `unknown` and `x2` is not assignable to `x3`.

In addition, I think this would fail at runtime because [the imports are missing](https://github.com/gcanti/io-ts/blob/1f23c7c4936690506eda3e1f7ad0066e84aa8bb1/src/Decoder.ts#L11-L23) [the required `.js` extensions](https://nodejs.org/api/esm.html#mandatory-file-extensions).

Any thoughts?
