### ISSUE TITLE
Is instanceOf a bad idea?

### ISSUE THREAD

**Issue by pelotom** [gcanti/io-ts#66]
Hello, [a PR was submitted to Runtypes](https://github.com/pelotom/runtypes/pull/23) to add an `InstanceOf` type. I recalled that at one time you had such a construct in `io-ts` so I went to look at how it was implemented for reference and saw that it was no longer there. Looks like it [was removed way back in version 0.1.0](https://github.com/gcanti/io-ts/blob/11ef27725622bb74c7eaefadfa166beb13393e79/CHANGELOG.md#010) without much explanation. I'm curious why you removed it, is it a bad idea?

**Comment by gcanti** [comment]
Hi!

IIRC it was a feature ported from flow-io which didn't align well with the structural nature of the type system

**Comment by breathe** [comment]
Hi -- I'm the one who tried to submit the InstanceOf PR -- I'm trying to digest and learn from your comment ...  After much pondering I'm thinking that the non-alignment problem you refer to is that it is possible for an object to statically type-check against the InstanceOf<T> if its structurally compatible with T but then fail to typecheck at runtime (because its not an instanceof T)?

If I'm right in understanding the issue -- I seem to have a use-case for wanting to enforce the instanceof requirement at runtime (despite the fact that its not possible to cause type errors for statically compatible-but-not-instance-of T's ... I'd like to get that failure at runtime and have more confidence the constructor codepath was invoked ...) ...  Maybe I'm wrong to think that I want this ...?

It seems to me like a useful pattern in some cases to cram various runtime checks into a constructor() for a type and then be able to at least detect cases where somebody avoided invoking that  constructor ...  I suppose there are other ways to avoid the constructor that even the runtime check would miss by fiddling with prototype chain -- but I'm not worried about that so much as finding simple scenarios where  structurally compatible object literals were used when I wanted instanceof T's ...

**Comment by gcanti** [comment]
> its not possible to cause type errors for statically compatible-but-not-instance-of T's

Exactly. Also keep in mind that tha main use case of io-ts is validating JSON payloads, so an `instanceof` check makes even less sense.

However io-ts could be used in 2 additional use cases

- validating values produced by code that you own (seems your use case)
- validating values produced by code that you don't own (for example values coming from another TypeScript library)

Let's talk about the former

> It seems to me like a useful pattern in some cases to cram various runtime checks into a constructor() for a type

The question is: what you do if the runtime checks fail in the constructor? I guess the only thing you can do is throwing, which should be always avoided in favour of total functions (for example returning an `Option` or an `Either`).

But *why* the runtime checks are failing? Likely because we are handling a refinement. Let's see an example, a range

```ts
// MyRange.ts
export class MyRange {
  constructor(public readonly start: number, public readonly end: number) {
    if (start > end) {
      throw new Error('bad range')
    }
  }
}

// main.ts
import { MyRange } from './MyRange'

console.log(new MyRange(2, 1)) // throws
```

Runtime checks can be **lifted to static checks** by using smart constructors

```ts
import { Option, some, none } from 'fp-ts/lib/Option'

// not exported
class MyRangeImpl implements MyRange {
  public readonly _tag: 'MyRange' = 'MyRange'
  constructor(public readonly start: number, public readonly end: number) {} // <= no runtime checkes here
}

export interface MyRange {
  readonly _tag: 'MyRange' // <= faking nominal types
  readonly start: number
  readonly end: number
}

// smart constructor: note that this function is total
export function createRange(start: number, end: number): Option<MyRange> {
  return start > end ? none : some(new MyRangeImpl(start, end))
}
```

**Comment by breathe** [comment]
Thanks very much for the explanation!!

That pattern does seem better to me in most cases -- especially if you are in a functional codebase (not using OO inheritance) and the consumers of your code are also using a typed language.  Will there be a meaningful runtime error if somebody does createRange(5,0).start from untyped code though?  (In my case, code that's not owned by me that calls into my code without type checking).

Re-summarizing again for my own understanding: InstanceOf<T> isn't a great idea because:
- InstanceOf<T> lies about its static type: statically its actually IsStructuralType<T> where dynamically its InstanceOf<T> ...
- funneling people toward enforcing constraints at runtime in the constructor() is a bad idea because all you can do is throw if there is a constraint violation (that's exactly what I was doing/trying to do).  Not including support for this pattern pushes people towards the more correct functional approach where you lift the runtime constraint validation into a correct static representation.

I greatly appreciate the response!  And the io-ts and fp-ts libraries look amazing.  In my case I'm new to typescript and trying to introduce typescript to a team of developers with a lot of java experience (and the same form of minimal javascript-because-i-had-to experience that everyone used to have before typed javascript showed up).  I came across the RunTypes library before this one and it seemed simpler for me to digest what it was/how to use it.  I'm a little worried about needing to sell the benefits of functional programming style as part of up-front migration cost to typescript though ...  If I switch to io-ts and adopt the above pattern I think I will end up with Either<ValidationError[], MyData>'s spreading pretty far into codebase as we iterate ...  My expectation is we'll get a lot of modeling problems wrong for awhile and an easily organized pattern of for adding runtime constraint enforcement will be needed to ease learning-while-debugging curve ...

Maybe initially using Option<MyRange>'s that lie about being total and actually throw error's (with TODO: statements saying to remove the throwing behavior when the untyped code is gone ...) wouldn't be such a bad direction ...?
